#!/bin/bash
set -e
cd /opt/agentic-framework

if [ ! -d .git ]; then
  git init
  git add -A
  git commit -m "Initial commit v3.0"
fi

git config user.email "deploy@agentic-framework.local"
git config user.name "Agentic Deploy"

# Add GitHub remote for generated code
if ! git remote | grep -q "origin"; then
  # Try to add the GitHub remote (will fail gracefully if already exists)
  git remote add origin https://github.com/landonking-gif/ai_final.git 2>/dev/null || true
fi

# Ensure the workspace directory exists and has its own git repo
mkdir -p workspace/ralph-work
cd workspace/ralph-work

if [ ! -d .git ]; then
  git init
  git config user.email "ralph@agentic-framework.local"
  git config user.name "Ralph AI Agent"
  
  # Add GitHub remote for ralph-work
  git remote add origin https://github.com/landonking-gif/ai_final.git 2>/dev/null || true
  
  # Create initial commit
  echo "# Ralph AI Generated Code" > README.md
  echo "" >> README.md
  echo "This directory contains code generated by the Ralph AI agent." >> README.md
  echo "Each subdirectory represents a completed user story." >> README.md
  git add .
  git commit -m "Initialize ralph-work repository" || true
fi

cd /opt/agentic-framework

if ! git remote | grep -q "openclaw"; then
  git remote add openclaw-upstream https://github.com/opencodelabs/openclaw.git 2>/dev/null || true
fi

cat > sync-openclaw.sh << 'SYNCEND'
#!/bin/bash
cd /opt/agentic-framework
git fetch openclaw-upstream main 2>/dev/null || exit 0
COMMITS=$(git log HEAD..openclaw-upstream/main --oneline 2>/dev/null | wc -l)
if [ "$COMMITS" -gt 0 ]; then
  git branch openclaw-backup 2>/dev/null
  git merge openclaw-upstream/main --no-edit && sudo docker compose build && sudo docker compose up -d || git merge --abort
fi
SYNCEND

chmod +x sync-openclaw.sh
(crontab -l 2>/dev/null | grep -v sync-openclaw; echo "0 */6 * * * /opt/agentic-framework/sync-openclaw.sh") | crontab - 2>/dev/null || true
echo "Git configured"
